# Java Gradle CircleCI 2.0 configuration file
version: 2
jobs:
    check:
        machine:
            image: ubuntu-2004:202010-01

        working_directory: ~/repo

        environment:
            TERM: dumb

        steps:
            - checkout
            - run: git config --global user.email "malecki.maciej@gmail.com"
            - run: git config --global user.name "Maciej Malecki"
            - run: git remote rm origin
            - run: git remote add origin https://maciejmalecki:${GITHUB_TOKEN}@github.com/c64lib/asm-ka.git
            - run: ./check.sh

    publish:
        docker:
            - image: cibuilds/github:0.10
        steps:
            - checkout
            - run: mkdir out
            - run: ./download.sh
            - run: cp KickAss.jar out
            - run:
                name: "Publish KickAss files on GitHub (asm_ka)"
                command: |
                    ls ./out
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./out

workflows:
    version: 2
    commit:
        jobs:
            - check
    check-new-release:
        triggers:
            - schedule:
                cron: "0 22 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - check
    publish-new-release:
        jobs:
            - publish:
                filters:
                    branches:
                        ignore:
                            - master
                    tags:
                        only:
                            - /^([0-9]+)\.([0-9]+)$/
